version: '3.7'

services:
  client:
    container_name: svelte_client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/build
    ports:
      - 3000:3000
    command: npm run prod
    restart: always
  server:
    container_name: svelte_server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 8000:8000
    command: npm run dev
    restart: always
volumes:
  client-build:
networks: 
  default:
     name: svelte